CREATE TABLE songs.playlist(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    RELEASE_YEAR INTEGER NOT NULL
);

CREATE TABLE songs.song(
     ID BIGINT NOT NULL PRIMARY KEY,
     NAME VARCHAR(255) NOT NULL,
     ARTIST VARCHAR(255) NOT NULL,
     DURATION DECIMAL(10, 2) NOT NULL,
     PLAYLIST_ID BIGINT NOT NULL REFERENCES songs.playlist(ID)
);

CREATE SEQUENCE songs.playlist_seq
    INCREMENT 1
    START 1000;

CREATE SEQUENCE songs.song_seq
    INCREMENT 1
    START 1000;