CREATE TABLE songs.artist(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    MONTHLY_LISTENERS VARCHAR(255) NOT NULL
);

CREATE SEQUENCE songs.artist_seq
    INCREMENT 1
    START 1000;