spring:
  datasource:
    url: ${JAVA_COURSE_DB_URL}
    username: ${JAVA_COURSE_DB_USERNAME}
    password: ${JAVA_COURSE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: songs
jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}